apache:
  image: nickbreen/wp-php:apache
  environment:
    VIRTUAL_HOST: "apache.example.com"
    NR_APP_NAME: "example-app"
    NR_INSTALL_KEY: example-key

fpm:
  image: nickbreen/wp-php:fpm
  environment:
    VIRTUAL_HOST: "fpm.example.com"
    NR_APP_NAME: "example-app"
    NR_INSTALL_KEY: example-key
